package com.dmdev.entity;

import lombok.*;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Data
@EqualsAndHashCode(of = "name")
@ToString(exclude = "userChats")
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class Chat {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String name;

    @Builder.Default
    @OneToMany(mappedBy = "chat")
    private List<UserChat> userChats = new ArrayList<>();
//    private Set<UserChat> userChats = new HashSet<>();


//    WITHOUT AUTOGENERATED SYNTHETIC KEY IN users_chat TABLE
//    @Builder.Default
//    @ManyToMany(mappedBy = "chats")
//    private Set<User> users = new HashSet<>();
}
